name := DVDS2
debug := 1

derived_files := data/dvds.png.tiles data/dvds.png.palette

data/dvds.png.tiles: tiles_flags = -v -D
data/dvds.png.palette: palette_flags = -v -C 4

libsfx_dir := ../libsfx
include $(libsfx_dir)/libsfx.make