# Name
name		:= 4beep
debug		:= 1

# Derived data files
#derived_files	:= data/4beep.palette data/2beep.palette data/4beep.tiles data/2beep.tiles data/4beep.map data/2beep.map

derived_files	:= data/mita1.pal data/mita2.pal data/mita_tl.img data/mita_tl.img data/mita_tr.pmap data/mita_tr.pmap
derived_files	:= data/mita_bl.img data/mita_bl.img data/mita_br.pmap data/mita_br.pmap

# Include libSFX.make
libsfx_dir	:= ../libSFX
include $(libsfx_dir)/libSFX.make
